# Generated by Django 6.0.4 on 2026-05-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
        ('media', '0002_alter_image_image_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='users', to='explore.country'),
        ),
    ]
