# Generated by Django 6.0.4 on 2026-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2', models.CharField(max_length=10)),
                ('alpha3', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
    ]
